### ISSUE TITLE
Still appears to not be working after update

### ISSUE THREAD

**Issue by JoelleEmmily** [Taknok/youtube-auto-like#72] opened 2022-10-31 20:57 UTC
**Expected Behavior**
Give a thumbs up to youtube creator video 

**Actual Behavior**
Addon does not auto-apply thumbs up

**To Reproduce**
1. Browse to video
2. Check white allow list
3. Be sure both human readable as well as hex name are in list
4. Restart Firefox
5. Attempt to remove null entry at bottom of list
6. Restart Firefox
7. Check update
8. Complain on GitHub

**Screenshots**
Not applicable

**Logs**
# Where

**Specification**
 - OS: Windows 10
 - Browser version: [e.g. Firefox 106,0.2 64
 - What've the new one is
 - YouTube Premium: Eff no
 - Youtube Player: All
 - Youtube Country: Canada

**Comment by Taknok** [comment] 2022-10-31 22:29
Nooo T.T (step 9 dev cry)
Can you send the logs please ? https://youtu.be/C4fQXRYwbrs?t=70

**Comment by JoelleEmmily** [comment] 2022-10-31 22:40
[The_Konomi_Code.zip](https://github.com/Taknok/youtube-auto-like/files/9905452/The_Konomi_Code.zip)

**Comment by JoelleEmmily** [comment] 2022-10-31 22:40
Should be an A

**Comment by Divin1ty666** [comment] 2022-11-01 09:06
I can confirm that if add-on is set to "Instant like" it may no add "like" sometimes(like 50\50%) for some reason. But after I switched it to "Custom timer" > Percentage (set to 3) it started to add likes all the times.

**Comment by Taknok** [comment] 2022-11-01 15:46
@JoelleEmmily Do you have the new paper youtube ? Or the "old" material youtube ? New paper youtube have those rounded buttons :
![image](https://user-images.githubusercontent.com/12498020/199275814-9fb8e623-691c-4a5c-9548-5f4868fba4ac.png)

@Divin1ty666 Same question paper or material ? Could you provide the logs when it is working and logs when it is not please ?

**Comment by Fraeksn** [comment] 2022-11-01 18:55
same for me and i got the new design.
but the % and minute like is also not working for me
[logs.zip](https://github.com/Taknok/youtube-auto-like/files/9913202/logs.zip)

**Comment by Taknok** [comment] 2022-11-01 21:06
Ok @Fraeksn Thank. It is strange because the material script is starting (log are from `liker-material.js`) instead of the paper one (`liker-paper.js`). The issue may be related to this. I will look into this.

**Comment by Taknok** [comment] 2022-11-02 10:16
Hi,
I just pushed a new version to the [dev branch](https://github.com/Taknok/youtube-auto-like/tree/dev). Could you tried it and tell me if it is working on the new paper version ?
How to: https://www.youtube.com/watch?v=C4fQXRYwbrs

**Comment by ReiNasc** [comment] 2022-11-02 12:14
Thank you for the response on my Firefox Add-Ons review. Congratulations for the excellent work. I inform you that, when turning off and on the extension, it marks the like and does not work anymore afterwards. Waiting for the fix, thanks.

**Comment by Taknok** [comment] 2022-11-02 18:20
Pushed on Firefox store as 3.6.1

**Comment by JoelleEmmily** [comment] 2022-11-03 02:08
YAY! Appears to be working after the last patch! Hand shakes, back slaps, and hookers all around!

**Comment by Taknok** [comment] 2022-11-03 09:50
Ok, good. I keep this issue open and will close it in 7 days if nothing else is reported :)

**Comment by Elrew** [comment] 2022-11-07 14:44
I know this is for the auto-like extension but I didn't see one for the dislike, and that is the one that is broken for me. I did try your auto-like dev branch and that works for liking.

**Closed** 2022-11-12 13:30 UTC
